### ISSUE TITLE
Margins in dynamic mode not correct, Win11

### ISSUE THREAD

**Issue by tdw46** [torchgm/RoundedTB#114]
The left margin of the taskbar in dynamic mode extends to the left side of the desktop, when it should be hugging the windows button. 
![image](https://user-images.githubusercontent.com/10996763/143138934-785a51ba-68fd-41aa-b7d5-80c16896f9a1.png)
[rtb.log](https://github.com/torchgm/RoundedTB/files/7591372/rtb.log)

**Comment by tdw46** [comment]
I just opened the config file and found that "IsCentred" is set to "false." I'm thinking it shouldn't be?

![image](https://user-images.githubusercontent.com/10996763/143139625-02ee2b92-9d59-4ce2-9d2b-667118cd90a1.png)

**Comment by torchgm** [comment]
Yeah, this is a known issue mentioned many-a-time by plenty of people - either setting the IsCentred option to true or setting the taskbar alignment to the left then back to the centre should work fine. Honestly the cause of this bug repeatedly eludes me because I fixed it with R3.1 on my machines and I'm no longer able to reproduce it but other people still keep running into it, so I'm imagining that it's an issue with actually reading the registry to check the alignment.

One day I'll be free of this curse...

**Comment by torchgm** [comment]
If you've not changed the taskbar alignment since encountering the error, could you please tell me what you can find for the `TaskbarAl` registry value in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced`?

**Comment by torchgm** [comment]
Oh nevermind I'm entirely stupid. If you've never set the alignment of the taskbar before, then the value doesn't exist, which returns null which is then cast to false which is interpreted as not centred - will fix ASAP

**Comment by mobeicanyue** [comment]
i have the same question

**Comment by Albonycal** [comment]
I have the same problem too

**Comment by Bingmang** [comment]
I have the same problem too
