### ISSUE TITLE
Taskbar is not show when the autohide feature and roundedTB are activated

### ISSUE THREAD

**Issue by Happytappy2108** [torchgm/RoundedTB#117]
hi!! i love this app, but on the last version the taskbar doesn't appear when the Windows autohide mode is active. If someone has the same problem, tell it to me please. If not, this issue could be only my problem😅

**Comment by torchgm** [comment]
Autohide isn't compatible with RoundedTB and as such I'm having to build my own custom autohide functionality. Since I have a bunch of other issues for this already I'll close this, but it is being worked on so don't worry. For now, either use autohide or RoundedTB, but they won't work properly together.

**Comment by TechStudent11** [comment]
@torchgm Is there a working prototype? If so, I would happily test it out.

**Comment by torchgm** [comment]
@TechStudent11 Not yet, but soon! Still some rather devastating bugs that need to be ironed out first, and the UI options need to be implemented, but after that you'll be able to try it out!

**Comment by TechStudent11** [comment]
@torchgm alright! I'll be waiting. It's just a cool and useful feature. Right now, I'm using RoundedTB in dynamic mode and having more screen real-estate (and not clicking on random windows in the background) is really something I'd like to see.
