### ISSUE TITLE
When dragging cursor to the corner(bottom left) you can't click start anymore.

### ISSUE THREAD

**Issue by Harshmf** [torchgm/RoundedTB#13]
i tried the thing but instantly removed it. cause i was not able to click anything due to the corners not being click targets.

this behavior is still present on my laptop, even after I've uninstalled the thing.(please fix this i really don't wanna reinstall windows)

maybe let the corners still be click targets because muscle memory 

man this thing is driving me nuts can't click my apps or anything at all when the cursor is at the bottom of the screen.

**Comment by Harshmf** [comment]
man please fix this. i have really bad ocd and i'm driving myself crazy

**Comment by torchgm** [comment]
Aight, calm yourself down. If you just remove RTB without exiting it then it'll leave the taskbar exactly how it was configured until you restart Explorer/Windows. As for the click-targets being missing, this is Fitt's Law at play. Why don't the click targets extend past the edge? That's because the Start button is physically inside the taskbar, and the only way RoundedTB can work is by cutting off the corners and edges of the taskbar.

This means that the edges of the click targets are removed too, exposing the desktop behind. There isn't anything I can do about this functionality without replicating the entirety of the Start Menu's context menu from scratch using undocumented nasty API calls (and it still likely wouldn't be as reliable).

Since there's nothing I can do about this in any reasonable fashion then I guess I can only recommend you don't use RoundedTB. As for making sure it's uninstalled correctly, you can simply restart your laptop or just restart Explorer which will reset the taskbar. If you want to fix it without restarting Explorer/your laptop, you can also just reinstall RTB, set the margin and radius to zero, then apply that, then right-click the tray icon, select the Exit option, *then* uninstall it. However, this really won't make any difference and I'd recommend just rebooting.

**Comment by Harshmf** [comment]
i've set margins radius to 0 and then exited and uninstalled too. till the time i don't restart it works fine, but as soon i restart my laptop i can't click the corners again.
this is after i've exited and uninstalled the way you told.

**Comment by Harshmf** [comment]
bro I managed to fix the thing. i think the latest version of taskbarx also got rounded corners and somehow managed to get completely mess up some settings.
anyone thanks for your development.
