### ISSUE TITLE
Auto-hiding the taskbar is buggy, flickers and doesn't work properly.

### ISSUE THREAD

**Issue by catb0x** [torchgm/RoundedTB#26]
so when i open/show my taskbar it flashes from normal to rounded
is there a way to fix it (its annoying)

**Comment by torchgm** [comment]
As mentioned in the release notes, autohide support is currently in preview for this very reason. However, in the upcoming version of RoundedTB it should be a bit smoother.

**Comment by hsusanoo** [comment]
Updated to R3, the flashes are still there, but happen differently now:

![Twitching](https://user-images.githubusercontent.com/35850056/134803287-b7287ec0-5092-4133-8fdb-d52f2fe2d6e3.gif)

**Comment by torchgm** [comment]
Honestly, autohide is a mess - I've had to "deprecate" official compatibility with it for now because of how unstable it can be (as you seem to have found). It's currently listed in the known issues as being very experimental. The issue comes from it literally moving the taskbar up and down, and also requiring the top row of pixels to always be visible to be able to "summon" it back.

I have a couple of ideas on how to "fix" it but none of them managed to make it into R3 unfortunately. R4 will consist of a complete rewrite of a lot of the internal logic, which became very messy throughout R3. Perhaps I'll find a better solution in doing so. Failing that, my next idea will be always leaving a row of pixels visible as part of the region when autohide is enabled, then scrapping all the actual logic used for detecting when the taskbar is moving like that. The major downside of this, of course, is leaving a row of pixels at the bottom that are always present, regardless whether or not the taskbar is visible.

**Comment by torchgm** [comment]
Closing in favour of #36 as it's got a bit more detail in it - issue is still an issue though!
