### ISSUE TITLE
Align the app with the fitts law

### ISSUE THREAD

**Issue by eguif** [torchgm/RoundedTB#27]
The app looks very promising, congratulations on the work
I noticed you are working on updates
An update that complies with Fitts law would be very welcome.

[Fitts law on Wikipedia](https://en.wikipedia.org/wiki/Fitts%27s_law)

This law is very much linked to the usability of something where it states something relatively simple "that the time needed to move quickly from a starting position to a final position is proportional to the size of the target object".

I will demonstrate with the two gifs below

![respecting fitts law](https://user-images.githubusercontent.com/25402156/128571566-ae8cfb65-5eef-42de-9bc1-1777dfcd8d6c.gif)
_According to the Fitts Law_

![not respecting fitts law](https://user-images.githubusercontent.com/25402156/128571965-fe766d43-9f56-47ff-b49f-35e0a3e779e7.gif)
_Does not comply with the Fitts Act_

It ends up taking longer to access the start menu with the mouse when the click area ends up being reduced taking longer to access it
The solution, IF it is possible to change only visually when entering margin and corner radius values without affecting the click area

**Comment by torchgm** [comment]
I'm aware of the violation of Fitt's law but the only way to actually achieve this would be to draw an invisible window behind the taskbar that then sends keypresses when clicked/right-clicked to emulate the start button. Due to how Windows 11 has retooled the taskbar, tracking the position of the start menu is significantly more difficult. On top of this, I'd then have to deal with custom start menus as well, and it'd just become a bit of a headache.

It's also worth noting that a lot of people (including myself) apparently use the gap as a way to access the desktop context menu without minimising/hidingopen windows, so outright blocking this functionality wouldn't be ideal. As with a lot of these things, I'm not saying no, but right now it's really not the focus. If I find a magically easy way to implement it then it'll certainly make it into a release, but as of now there's not much I can realistically do I'm afraid.

**Comment by eguif** [comment]
Thank you for your feedback
