### ISSUE TITLE
Input fields should accept decimal numbers

### ISSUE THREAD

**Issue by eguif** [torchgm/RoundedTB#28]
I tested both value input fields
They only accept integer data type.
I believe it might be possible to change both fields to accept values in float type

**Comment by torchgm** [comment]
This isn't possible - the API functions accept integers and if you try to push anything that's not an integer into them then they'll break. The values in the configuration options are measured in logical pixels, which is a physical pixel multiplied by your display's scale factor. For example a 3840x2160 monitor at 200% scaling has a logical resolution of 1920x1080.

Technically it'd be possible to offer slightly more granularity for scale factors above 100%, but this would mess with multi-monitor setups that have mixed scale factors. Another example - the Windows 10 taskbar at 100% scaling is 80 physical pixels tall. At 200% scaling it's 160 physical pixels tall, but still only 80 logical pixels tall.

Assuming RTB used physical pixels instead of logical pixels, say you have two monitors, one at each scale factor. Let's also assume you a margin of 4px. On the 100%sf monitor, that'll remove 4 pixels from the top of the taskbar, and 4 pixels from the bottom of the taskbar, which is 8px in total and 10% of the taskbar's height.

On the 200%sf monitor though, the taskbar is actually 160px tall since it's been scaled, well, by 200%. Removing four pixels from the top and bottom would only be 5% of the taskbar's height, which would mean that the taskbars would look to be different. This is obviously something I want to avoid, hence why I use logical pixels.

I'll leave this open as I might add a secret config option to use physical pixels instead, but it likely won't get a GUI option and will have to be enabled from the json file manually due to such a low demand.

**Comment by eguif** [comment]
All right torchgm. Thanks for the detailed answer

**Comment by torchgm** [comment]
Closing this as after some recent changes implementing fractions would be a nightmare I'm afraid.
