### ISSUE TITLE
Documentation & new splash screen

### ISSUE THREAD

**Issue by Davikar** [torchgm/RoundedTB#6]
Adding margin to the taskbar just cuts the icons off. It's especially noticeable if you go past 20.

![Screenshot 2021-06-03 174004](https://user-images.githubusercontent.com/8229634/120672789-e7e8e000-c492-11eb-9524-70505983b115.png)

**Comment by torchgm** [comment]
Margin is measured in logical pixels/screen units (physical pixels * scale factor), it's not supposed to make the taskbar float. Typing in 20 will cut off 20 screen units from every side of the taskbar.

Making it float is unfortunately not really possible due to the fact that since Vista the taskbar is unable to be unregistered as an appbar or moved/resized freely by other applications. It is technically possible to set all the components of the taskbar as the children of another window, but this renders it unstable and can cause Explorer to hang.

I'll leave this open as I do need to better-document how this margin works.

**Comment by torchgm** [comment]
Repurposing this issue to reflect all documentation:

 - new welcome splash screen w. explanation for how RTB works 
 - actually set the correct default settings to avoid confusion
 - highlight preview features & warn when first enabled
