### ISSUE TITLE
Jagged rounded corners and missing pixels on the right side

### ISSUE THREAD

**Issue by RavenMacDaddy** [torchgm/RoundedTB#96]
At least on a 1080p display, the rounded corners are jagged, so I made a comparison to show how this can be improved:

Before:

![image](https://user-images.githubusercontent.com/67732686/141658049-23645ca7-9b18-4381-b1b5-91fd4435b29f.png)

After:

![image](https://user-images.githubusercontent.com/67732686/141658069-1a3d9cca-5501-4bfa-9636-275f9ed72d66.png)

Obviously this should be tweaked with proper anti-aliasing/shading, but you get the idea.

---

Next up is the right side, which is clearly missing the corresponding surrounding pixels, seen here:

![image](https://user-images.githubusercontent.com/67732686/141658360-f4bde8d4-c430-4e7b-a7dd-6084aab90eb4.png)

**Comment by awesomelewis2007** [comment]
What's your resolution right now?

**Comment by torchgm** [comment]
Being off by 1px is actually because the taskbar is *slightly* not-centred but I might be able to add some weighting to that. As for the lack of anti-aliasing and the rounding algorithm, that's handled by a Windows API and is out of my control. Usually increasing/decreasing the corner radius by 1 will remove those sharper edges.
