### ISSUE TITLE
System tray: Too many pixels on the right side and improving the left

### ISSUE THREAD

**Issue by RavenMacDaddy** [torchgm/RoundedTB#97]
The following is on a 1080p screen for reference.

---

First the right side, comparison with a rough sketch on how to improve it.

Before:

![image](https://user-images.githubusercontent.com/67732686/141658529-733bc095-9aaa-4e68-9ebb-1084612b36b4.png)

After: 

![image](https://user-images.githubusercontent.com/67732686/141658516-9fa2eb28-4be7-4f85-b9b7-426abb65ce79.png)

---

Next, since we've the straight markings that light up when hovering over for example the up arrow on the left side, is it possible to do the following?: 

Before: 

![image](https://user-images.githubusercontent.com/67732686/141658703-d4293d42-591b-49d7-82bf-00426a881496.png)

After:

![image](https://user-images.githubusercontent.com/67732686/141658627-e69074ea-47ec-4e51-99e8-06522ee833c2.png)

Notice how:

- The left side has been adjusted to remove the jagged edges by providing the proper amount of pixels for the rounded corners.
- The margin to the left has been adjusted since it was two rows of pixels too many.
- Surrounding darker pixels have been added as a single row of pixels above, below, and also a single pixel on the top and bottom right corners to create rounded corners.

**Comment by torchgm** [comment]
You should really make independent issues for all these so they can be addressed better. However, none of this is really possible. As mentioned in #96, the rounding logic is handled by Windows using existing APIs so there's not much I can do to tidy up the corners I'm afraid.

As for modifying things *on* the taskbar, there's not much that I can do. Moving or resizing things on the taskbar is incredibly restricted, the fact that RoundedTB works at all is because it doesn't actually touch the taskbar itself. Once XAML debugging is better-documented I might revisit it, but for now you might want to try out the advanced margin options.

**Comment by RavenMacDaddy** [comment]
Fair point, I'll keep that in mind.
